<?php
// generated by Poedit from woocommerce-files-upload-it_IT.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'it_IT','pot-creation-date'=>'2025-10-03 09:51+0200','po-revision-date'=>'2025-10-03 09:51+0200','translation-revision-date'=>'2025-10-03 09:51+0200','project-id-version'=>'WooCommerce Upload Files','x-generator'=>'Poedit 3.7','messages'=>['You must accept the disclaimer'=>'Devi accettare la liberatoria','Allowed file types: '=>'Estensioni permesse:','Warning'=>'Attenzione']];
